Getting data

In [ ]:
import pandas as pd

,Date,Id,Players,Time,Seconds,Link
0,2025-10-03,y2r3r29m,Blobdoodles,1h 33m 26s,5606.0,https://www.speedrun.com/silksong/runs/y2r3r29m
1,2025-10-06,zn54ov9z,Vespher,1h 01m 02s,3662.0,https://www.speedrun.com/silksong/runs/zn54ov9z
2,2025-10-21,yw58vvny,Aribuge,55m 40s,3340.0,https://www.speedrun.com/silksong/runs/yw58vvny
3,2025-11-06,zx56ppkm,Remto,53m 17s,3197.0,https://www.speedrun.com/silksong/runs/zx56ppkm
4,2025-11-08,zg9gv7jm,Remto,52m 53s,3173.0,https://www.speedrun.com/silksong/runs/zg9gv7jm

In [9]:
silksong_wr_df = pd.read_csv("Silksong_any%_wr_times.csv").drop("Link", axis = 1)
celeste_wr_df = pd.read_csv("Celeste_any%_wr_times.csv").drop("Link", axis = 1)

In [10]:
celeste_wr_df.tail()

           Date        Id        Players           Time   Seconds
116  2024-03-08  yldkkv2m  secureaccount  25m 05s 350ms  1505.350
117  2024-03-12  ydn5pk0m  secureaccount  24m 58s 023ms  1498.023
118  2024-11-21  z0qv5e9m  secureaccount  24m 51s 495ms  1491.495
119  2026-02-02  mr5p4e2y  secureaccount  24m 51s 036ms  1491.036
120  2026-04-09  m7j6gp5m  secureaccount  24m 48s 843ms  1488.843